# Site settings
name: Rick Winfrey
email: rick.winfrey@gmail.com
title: "Rick Winfrey"
description: "Rick Winfrey"

#host: '127.0.0.1'

markdown: kramdown
#permalinks: /:categories/:title

# http://en.wikipedia.org/wiki/Words_per_minute#Reading_and_comprehension
words_per_minute: 180
headings: ["About", "Writings"]

# Sass settings
sass:
  sass_dir: _sass
  style: :compressed

# code highlighting
highlighter: pygments
